### ISSUE TITLE
Removing swank dep

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/ndebug#3] opened 2022-07-22 04:22 UTC
Seems quite easy, really, although it may not work with ABCL:

```lisp
(defclass slime-input-stream (fundamental-character-input-stream)
  ((input-fn :initarg :input-fn)
   (buffer :initform "") (index :initform 0)
   (lock :initform (make-lock :name "buffer read lock"))))

(defun make-output-stream (write-string)
  (make-instance 'slime-output-stream :output-fn write-string))

(defun make-input-stream (read-string)
  (make-instance 'slime-input-stream :input-fn read-string))
```

For ABCL:

```lisp
(progn
  (defimplementation make-output-stream (write-string)
    (ext:make-slime-output-stream write-string))

  (defimplementation make-input-stream (read-string)
    (ext:make-slime-input-stream read-string
                                 (make-synonym-stream '*standard-output*))))
```

**Comment by aartaka** [comment] 2022-07-22 08:00
I mean, a reasonable alternative that I list in the README is using `trivial-gray-streams`. They should even work on ABCL. Swank uses them too.

The problem is: implementation of these function-based streams takes some hundreds of code lines in Swank, so I'm not sure that
- It's ethical to copy it, or
- It's reasonable to re-implement it :thinking:

**Comment by Ambrevar** [comment] 2022-07-22 08:36
SLIME is GPL2+.

What's the problem with the aforementioned suggestion?

**Comment by Ambrevar** [comment] 2022-07-22 10:01
> Well, that tells me nothing about the ability to copy-paste code as that I'm always uncertain about it in regards to any license xD

You cannot copy the code I believe :/

**Comment by aartaka** [comment] 2022-07-22 11:14
> So what's the purpose of `slime-output-stream` compared to any other `fundamental-character-output-stream`? `flexi-streams:flexi-output-stream` could do the job, no? That said, I'm not sure this dep would be any lighter than Swank...

The purpose of `slime-output-stream` is to allow calling a function to get/send contents to the stream, instead of getting/setting mere characters to some in-memory/file string/array. We need that to invoke an action at least when `*query-io*` needs to prompts the user. Using any others streams but function-invoking ones (of which I only know Swank ones) makes it impossible to e.g. open a prompt-buffer when debugger starts prompting. I mean, we can spawn a thread to watch the contents of some stream or string and act based on those, but that's highly unreliable.

Thus, we have four alternatives:
- Use Swank.
- Re-implement function-based streams with `trivial-gray-streams` (which `fundamental-character-output-stream` and the like actually belong to, as they didn't make it to ANSI spec.)
- Find another library with function-invoking streams.
- Somehow hack things up without any of those (which I don't believe to be sane).

**Comment by Ambrevar** [comment] 2022-07-22 12:32
Option 3 seems ideal, but until we find something, then I can only see option 2.

**Comment by aartaka** [comment] 2022-09-04 17:57
0498d33de226723ffd72c368f9ee3b73550128b7 finally implements quite basic yet sufficient set of stream methods to stop depending on Swank! Closing this, as is seems to be completed.

CC @Shinmera, you've said you want to have a debugger library free of Swank. Now you have it :D

**Comment by Shinmera** [comment] 2022-09-04 17:59
Sweet

**Closed** 2022-09-04 18:06 UTC

**Comment by Ambrevar** [comment] 2022-09-05 08:17
Nice, thanks!
